/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ssii.foomap.api;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-11T08:16:31.504Z")

@Api(value = "geodatabase", description = "the geodatabase API")
public interface GeodatabaseApi {

    @ApiOperation(value = "获取图层数据,GeoJSON格式", nickname = "getGeoData", notes = "", response = String.class, tags={ "地理数据","图层数据", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK,返回数据为GeoJSON格式的字符串", response = String.class) })
    @RequestMapping(value = "/geodatabase/geojson/{name}",
        method = RequestMethod.GET)
    ResponseEntity<String> getGeoData(@ApiParam(value = "用户登录成功后的Token" ,required=true) @RequestHeader(value="authoration", required=true) String authoration,@ApiParam(value = "图层数据源名称，对就数据库表名称",required=true) @PathVariable("name") String name,@ApiParam(value = "查询关键字") @Valid @RequestParam(value = "keywords", required = false) String keywords,@ApiParam(value = "点查询的坐标点") @Valid @RequestParam(value = "point", required = false) List<BigDecimal> point,@ApiParam(value = "地图显示范围") @Valid @RequestParam(value = "bounds", required = false) List<BigDecimal> bounds,@ApiParam(value = "框选查询的框") @Valid @RequestParam(value = "box", required = false) List<BigDecimal> box,@ApiParam(value = "自定义查询，通过自定义sql where=后面的字符来进行查询") @Valid @RequestParam(value = "where", required = false) String where);

}
