/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ssii.foomap.api;

import com.ssii.foomap.entity.MapEntity;
import com.ssii.foomap.model.MapOptions;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-11T08:16:31.504Z")

@Api(value = "map", description = "the map API")
public interface MapApi {

    @ApiOperation(value = "获取地图基础配制", nickname = "getMapConfigs", notes = "获取地图基础配制，包括坐标系、中心点等", response = MapEntity.class, tags = {"地图配制",})
    @ApiResponses(value = {@ApiResponse(code = 200, message = "OK", response = MapOptions.class)})
    @RequestMapping(value = "/map", method = RequestMethod.GET)
    ResponseEntity<MapEntity> getMapConfigs(@ApiParam(value = "用户登录成功后的Token", required = true) @RequestHeader(value = "authoration", required = true) String authoration);


    @ApiOperation(value = "配制地图基础信息", nickname = "setMapConfigs", notes = "", tags = {"地图配制",}, response = MapEntity.class)
    @ApiResponses(value = {@ApiResponse(code = 200, message = "OK，配制成功")})
    @RequestMapping(value = "/map", method = RequestMethod.POST)
    ResponseEntity<MapEntity> setMapConfigs(@ApiParam(value = "用户登录成功后的Token", required = true) @RequestHeader(value = "authoration", required = true) String authoration, @ApiParam(value = "", required = true) @Valid @RequestBody MapEntity options);

}
